version: '3.3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    volumes:
      - .:/usr/src/express-app
      - ./node_modules:/usr/src/express-app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
